# create a variable for token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoibWVsaXNzYUB1c2VyLmNvbSIsIm1vdGRwYXNzZSI6IiQyYiQxMCQ5cTBIOURQeGo1WjdnaUUvNlAwLk8uU29ZbVdaNzhUNlVtOGw5UUJDUWNZQnQ2TUJHVXBBeSIsImlhdCI6MTc4MDU3Nzg3Mn0.fzEdfX_4ZyTwF6wz9RIrPBUjb6e9NwnWXXkS107qqSI

### Register
POST http://localhost:1992/auth/local/register
Content-Type: application/json

{
  "pseudo": "melissa@user.com",
  "motdpasse": "admin1234"
}

### Login
POST http://localhost:1992/auth/local
Content-Type: application/json

{
  "pseudo": "melissa@user.com",
  "motdpasse": "admin1234"
}

### Get all voitures
GET http://localhost:1992/voitures
Authorization: Bearer {{token}}

### Get one voiture
GET http://localhost:1992/voitures/1
Authorization: Bearer {{token}}

### Create voiture
POST http://localhost:1992/voitures
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Peugeot 208",
  "price": 15000
}

### Update voiture
PATCH http://localhost:1992/voitures/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Peugeot 308",
  "price": 18000
}

### Delete voiture
DELETE http://localhost:1992/voitures/1
Authorization: Bearer {{token}}
