# btoa("admin:admin1234") = YWRtaW46YWRtaW4xMjM0
# Authorization: Basic YWRtaW46YWRtaW4xMjM0

### Get all voitures (public)
GET http://localhost:1992/voitures/get-all

### Get one voiture (public)
GET http://localhost:1992/voitures/get-this-one?id=1

### Create voiture (Basic Auth requise)
POST http://localhost:1992/voitures/create
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "data": {
    "name": "Peugeot 208",
    "price": 15000
  }
}

### Update voiture (Basic Auth requise)
PATCH http://localhost:1992/voitures/update/1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM0

{
  "data": {
    "name": "Peugeot 308",
    "price": 18000
  }
}

### Delete voiture (Basic Auth requise)
DELETE http://localhost:1992/voitures/delete?id=1
Authorization: Basic YWRtaW46YWRtaW4xMjM0
